# Generated by Django 4.0.1 on 2022-03-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_wellfare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplements',
            old_name='qty_supplement',
            new_name='qty_supplements',
        ),
    ]
