# Generated by Django 4.0.1 on 2022-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_breed_farmpurpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='onboard_complete',
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='onboard_complete',
            field=models.BooleanField(default=False),
        ),
    ]
