# Generated by Django 4.0.1 on 2022-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_onboard_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmprofile',
            name='sales_units_dozen_carton',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='sales_units_half_dozen_carton',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='sales_units_single_eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='sales_units_trays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='trays_quantity',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='farm_sales_collections',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='farm_sales_deliveries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='farm_sales_markets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmprofile',
            name='farm_sales_roadside',
            field=models.BooleanField(default=False),
        ),
    ]
