# Generated by Django 4.0.1 on 2022-02-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_farmprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmprofile',
            old_name='user',
            new_name='user_profile',
        ),
    ]
