# Generated by Django 4.0.1 on 2022-03-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_farmprofile_farm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city_country',
            field=models.CharField(max_length=35),
        ),
    ]
