# Generated by Django 4.0.1 on 2022-03-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(max_length=50)),
                ('qty_supplement', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
            ],
            options={
                'verbose_name_plural': 'Supplements',
            },
        ),
    ]
