# Generated by Django 4.0.1 on 2022-04-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('health_and_welfare', '0002_administrationmethod_diseasesname_medicinesname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplements',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='doseage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
        ),
        migrations.AddField(
            model_name='supplements',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='supplements',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='qty_chicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='qty_cocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='qty_hens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='qty_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplements',
            name='vet_administered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplements',
            name='vet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplementsname',
            name='supplement_name',
            field=models.CharField(default='supplement 1', max_length=50),
            preserve_default=False,
        ),
    ]
