# Generated by Django 4.0.1 on 2022-03-29 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('health_and_welfare', '0002_rename_qty_supplement_supplements_qty_supplements'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasesNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Disease Names',
            },
        ),
        migrations.CreateModel(
            name='MedicinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_medicines', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
            ],
            options={
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='MedicinesNameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Medicine Names',
            },
        ),
        migrations.CreateModel(
            name='SupplementsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Supplement Names',
            },
        ),
        migrations.CreateModel(
            name='VaccinesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_vaccines', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
            ],
            options={
                'verbose_name_plural': 'Vaccines',
            },
        ),
        migrations.CreateModel(
            name='VaccinesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Vaccine Names',
            },
        ),
        migrations.DeleteModel(
            name='Supplements',
        ),
    ]
