# Generated by Django 4.0.1 on 2022-03-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('health_and_welfare', '0003_diseasesnamemodel_medicinesmodel_medicinesnamemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('qty_hens', models.IntegerField(blank=True, null=True)),
                ('qty_chicks', models.IntegerField(blank=True, null=True)),
                ('qty_cocks', models.IntegerField(blank=True, null=True)),
                ('qty_total', models.IntegerField(blank=True, null=True)),
                ('dose', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vet_administered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Recipients',
            },
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_supplements', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
                ('supplement_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_and_welfare.supplementsname')),
            ],
            options={
                'verbose_name_plural': 'Supplements',
            },
        ),
        migrations.RenameModel(
            old_name='VaccinesModel',
            new_name='Vaccines',
        ),
        migrations.RenameModel(
            old_name='DiseasesNameModel',
            new_name='DiseasesName',
        ),
        migrations.RenameModel(
            old_name='MedicinesNameModel',
            new_name='MedicinesName',
        ),
        migrations.DeleteModel(
            name='MedicinesModel',
        ),
        migrations.AddField(
            model_name='medicines',
            name='disease_protected_against',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_and_welfare.diseasesname'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='farm_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
        ),
        migrations.AddField(
            model_name='medicines',
            name='medicine_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_and_welfare.medicinesname'),
        ),
    ]
