# Generated by Django 4.0.1 on 2022-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0003_supplements_date_supplements_doseage_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplements',
            old_name='doseage_amount',
            new_name='dosage_amount',
        ),
    ]
