# Generated by Django 4.0.1 on 2022-04-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0004_rename_doseage_amount_supplements_dosage_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplements',
            name='qty_supplements',
        ),
        migrations.RemoveField(
            model_name='supplements',
            name='qty_total',
        ),
    ]
