# Generated by Django 4.0.1 on 2022-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0004_medicines_recipients_supplements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipients',
            name='recipients',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
