# Generated by Django 4.0.1 on 2022-03-29 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0005_alter_recipients_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administration_method', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Administration Methods',
            },
        ),
        migrations.RenameField(
            model_name='medicines',
            old_name='dose',
            new_name='doseage_amount',
        ),
        migrations.AddField(
            model_name='medicines',
            name='vet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicines',
            name='administration_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_and_welfare.administrationmethod'),
        ),
    ]
