# Generated by Django 4.0.1 on 2022-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0006_administrationmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicines',
            name='medicine_name_user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
