# Generated by Django 4.0.1 on 2022-05-05 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('health_and_welfare', '0006_supplements_dose_per_bird_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplements',
            name='dosage_amount',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplements',
            name='dose_per_bird',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplements',
            name='flock',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplements',
            name='supplement_name',
            field=models.CharField(default='fibre', max_length=50),
            preserve_default=False,
        ),
    ]
