# Generated by Django 4.0.1 on 2022-04-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0007_medicines_medicine_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='supplement_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplementsname', to='health_and_welfare.supplementsname'),
        ),
    ]
