# Generated by Django 4.0.1 on 2022-05-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0007_alter_supplements_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicines',
            old_name='doseage_amount',
            new_name='dosage_amount',
        ),
    ]
