# Generated by Django 4.0.1 on 2022-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0008_alter_supplements_supplement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='supplement_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
