# Generated by Django 4.0.1 on 2022-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0008_rename_doseage_amount_medicines_dosage_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='qty_total',
        ),
        migrations.AddField(
            model_name='medicines',
            name='dose_per_bird',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
