# Generated by Django 4.0.1 on 2022-04-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('health_and_welfare', '0009_alter_supplements_supplement_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicines',
            name='medicine_name_user',
        ),
        migrations.AddField(
            model_name='supplementsname',
            name='farm_profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplementsname',
            name='supplement_in_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
