# Generated by Django 4.0.1 on 2022-05-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('health_and_welfare', '0009_remove_medicines_qty_total_medicines_dose_per_bird'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='disease_protected_against',
            field=models.CharField(default='disease 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicines',
            name='dosage_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicines',
            name='flock',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicine_name',
            field=models.CharField(default='medicine', max_length=50),
            preserve_default=False,
        ),
    ]
