# Generated by Django 4.0.1 on 2022-04-16 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('profiles', '0009_alter_userprofile_city_country'),
        ('health_and_welfare', '0009_alter_supplements_supplement_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusesName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Virus Names',
            },
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='vaccines',
            options={},
        ),
        migrations.RenameField(
            model_name='vaccines',
            old_name='qty_vaccines',
            new_name='doseage_amount',
        ),
        migrations.RemoveField(
            model_name='medicines',
            name='medicine_name_user',
        ),
        migrations.AddField(
            model_name='supplementsname',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplementsname',
            name='supplement_in_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='administration_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health_and_welfare.administrationmethod'),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='flock',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccines',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='qty_chicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='qty_cocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='qty_hens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='qty_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='vet_administered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='vet_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='virus_protected_against',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='disease_protected_against',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
