# Generated by Django 4.0.1 on 2022-05-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('health_and_welfare', '0010_alter_medicines_disease_protected_against_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinesname',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
    ]
