# Generated by Django 4.0.1 on 2022-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0010_remove_medicines_medicine_name_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='disease_protected_against',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
