# Generated by Django 4.0.1 on 2022-04-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0011_alter_medicines_disease_protected_against'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipients',
        ),
    ]
