# Generated by Django 4.0.1 on 2022-05-16 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0012_rename_doseage_amount_vaccines_dosage_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccines',
            options={'verbose_name_plural': 'Vaccines'},
        ),
        migrations.AlterField(
            model_name='medicines',
            name='administration_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health_and_welfare.administrationmethod'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
