# Generated by Django 4.0.1 on 2022-05-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('health_and_welfare', '0013_alter_vaccines_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinesname',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
        migrations.AddField(
            model_name='virusesname',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
    ]
