# Generated by Django 4.0.1 on 2022-04-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0013_virusesname_alter_vaccines_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
