# Generated by Django 4.0.1 on 2022-04-11 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health_and_welfare', '0014_alter_vaccines_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccines',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
