# Generated by Django 4.0.1 on 2022-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0002_customuser_sign_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='onboard_complete',
            field=models.BooleanField(default=False),
        ),
    ]
