# Generated by Django 4.0.1 on 2022-02-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0003_customuser_onboard_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='onboard_complete',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
