# Generated by Django 4.0.1 on 2022-02-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAuth', '0004_remove_customuser_onboard_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
