# Generated by Django 4.0.1 on 2022-02-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('qty_egg_trays', models.IntegerField()),
                ('qty_egg_singles', models.IntegerField()),
                ('qty_total_eggs_laid', models.IntegerField()),
                ('qty_eggs_damaged', models.IntegerField()),
                ('qty_eggs_broken', models.IntegerField()),
                ('qty_eggs_personal_use', models.IntegerField()),
                ('qty_eggs_given_free', models.IntegerField()),
                ('weight_total_eggs_laid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_egg_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('qty_saleable_eggs', models.IntegerField()),
                ('egg_collection_notes', models.CharField(max_length=500)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('food_type', models.IntegerField()),
                ('amount_food_rem', models.IntegerField()),
                ('amount_food_added', models.IntegerField()),
                ('amount_water_rem', models.IntegerField()),
                ('amount_water_added', models.IntegerField()),
                ('feeding_notes', models.CharField(max_length=500)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
