# Generated by Django 4.0.1 on 2022-03-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0002_remove_eggcollection_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('disinfected', models.BooleanField(blank=True)),
                ('disinfectant', models.CharField(blank=True, max_length=250)),
                ('coop_cleaning_notes', models.CharField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='avg_egg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='egg_collection_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_egg_singles',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_egg_trays',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_broken',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_damaged',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_given_free',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_personal_use',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_saleable_eggs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_total_eggs_laid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='weight_total_eggs_laid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='feeding_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='food_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
