# Generated by Django 4.0.1 on 2022-03-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0003_coopcleaning_alter_eggcollection_avg_egg_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disinfectants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disinfectant_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Disinfectants',
            },
        ),
        migrations.RemoveField(
            model_name='coopcleaning',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='feedingtime',
            name='image_url',
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('qty_food', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
            ],
            options={
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.AlterField(
            model_name='coopcleaning',
            name='disinfectant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='regular_tasks.disinfectants'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regular_tasks.foods'),
        ),
    ]
