# Generated by Django 4.0.1 on 2022-03-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0004_disinfectants_remove_coopcleaning_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foods',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.RenameField(
            model_name='feedingtime',
            old_name='food_type',
            new_name='feed_type',
        ),
        migrations.RenameField(
            model_name='foods',
            old_name='food_name',
            new_name='feed_name',
        ),
    ]
