# Generated by Django 4.0.1 on 2022-03-08 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('regular_tasks', '0005_alter_foods_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggcollection',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='flock',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
            preserve_default=False,
        ),
    ]
