# Generated by Django 4.0.1 on 2022-03-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0007_alter_foods_options_remove_feedingtime_feed_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Feeds',
        ),
    ]
