# Generated by Django 4.0.1 on 2022-03-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0008_rename_foods_feeds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeds',
            options={'verbose_name_plural': 'Feeds'},
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='feed_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='regular_tasks.feeds'),
            preserve_default=False,
        ),
    ]
