# Generated by Django 4.0.1 on 2022-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('regular_tasks', '0009_alter_feeds_options_feedingtime_feed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingtime',
            name='flock',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks'),
            preserve_default=False,
        ),
    ]
