# Generated by Django 4.0.1 on 2022-03-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('regular_tasks', '0011_feedingtime_farm_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopcleaning',
            old_name='coop_cleaning_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='eggcollection',
            old_name='egg_collection_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='feedingtime',
            old_name='feeding_notes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='coopcleaning',
            name='coop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flock_management.coops'),
        ),
    ]
