# Generated by Django 4.0.1 on 2022-03-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('regular_tasks', '0012_rename_coop_cleaning_notes_coopcleaning_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopcleaning',
            name='coop',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='flock_management.coops'),
            preserve_default=False,
        ),
    ]
