# Generated by Django 4.0.1 on 2022-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0013_alter_coopcleaning_coop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_total_eggs_laid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
