# Generated by Django 4.0.1 on 2022-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0014_alter_eggcollection_qty_total_eggs_laid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcollection',
            name='avg_egg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_broken',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_damaged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_given_free',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_personal_use',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_saleable_eggs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='weight_total_eggs_laid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
