# Generated by Django 4.0.1 on 2022-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0015_alter_eggcollection_avg_egg_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_egg_singles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_egg_trays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
