# Generated by Django 4.0.1 on 2022-03-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0016_alter_eggcollection_qty_egg_singles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcollection',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
    ]
