# Generated by Django 4.0.1 on 2022-03-21 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('regular_tasks', '0017_alter_eggcollection_farm_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopcleaning',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='coopcleaning',
            name='coop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flock_management.coops'),
        ),
        migrations.AlterField(
            model_name='coopcleaning',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
