# Generated by Django 4.0.1 on 2022-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0017_alter_eggcollection_farm_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coopcleaning',
            name='coop',
        ),
        migrations.RemoveField(
            model_name='eggcollection',
            name='farm_profile',
        ),
        migrations.RemoveField(
            model_name='feedingtime',
            name='farm_profile',
        ),
        migrations.AddField(
            model_name='coopcleaning',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='eggcollection',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='coopcleaning',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollection',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
