# Generated by Django 4.0.1 on 2022-03-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0019_alter_eggcollection_qty_eggs_damaged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggcollection',
            name='qty_eggs_damaged',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
