# Generated by Django 4.0.1 on 2022-03-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0019_alter_eggcollection_farm_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopcleaning',
            name='disinfectant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regular_tasks.disinfectants'),
        ),
        migrations.AlterField(
            model_name='coopcleaning',
            name='disinfected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
