# Generated by Django 4.0.1 on 2022-03-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0020_alter_coopcleaning_disinfectant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disinfectants',
            name='disinfectant_name',
            field=models.CharField(max_length=30),
        ),
    ]
