# Generated by Django 4.0.1 on 2022-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0021_alter_disinfectants_disinfectant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disinfectants',
            name='disinfectant_name',
            field=models.CharField(max_length=40),
        ),
    ]
