# Generated by Django 4.0.1 on 2022-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0022_alter_disinfectants_disinfectant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
