# Generated by Django 4.0.1 on 2022-04-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0022_alter_disinfectants_disinfectant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeds',
            old_name='feed_name',
            new_name='feed_type',
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='food_total_setup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Food Total'),
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='water_total_setup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Water Total'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='feed_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
