# Generated by Django 4.0.1 on 2022-03-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0023_jstest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jstest',
            name='age',
        ),
    ]
