# Generated by Django 4.0.1 on 2022-04-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0023_rename_feed_name_feeds_feed_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedingtime',
            old_name='feed_type',
            new_name='feed_name',
        ),
        migrations.RenameField(
            model_name='feeds',
            old_name='feed_type',
            new_name='feed_name',
        ),
    ]
