# Generated by Django 4.0.1 on 2022-04-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('regular_tasks', '0024_remove_jstest_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingTimeSetUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('food_total', models.IntegerField(blank=True, null=True, verbose_name='Food Total')),
                ('water_total', models.IntegerField(blank=True, null=True, verbose_name='Water Total')),
                ('farm_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regular_tasks.feeds')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks')),
            ],
        ),
        migrations.DeleteModel(
            name='jsTest',
        ),
    ]
