# Generated by Django 4.0.1 on 2022-04-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0024_rename_feed_type_feedingtime_feed_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedingtime',
            old_name='food_total_setup',
            new_name='food_total',
        ),
        migrations.RenameField(
            model_name='feedingtime',
            old_name='water_total_setup',
            new_name='water_total',
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='amount_food_consumed',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of food consumed'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='feed_name',
            field=models.CharField(default='manual', max_length=50),
            preserve_default=False,
        ),
    ]
