# Generated by Django 4.0.1 on 2022-04-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0024_remove_jstest_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsTest',
        ),
    ]
