# Generated by Django 4.0.1 on 2022-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0025_rename_food_total_setup_feedingtime_food_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingtime',
            name='amount_water_consumed',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of water consumed'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_added',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of food added'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_rem',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of food remaining'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_water_added',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of water added'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_water_rem',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of water remaining'),
        ),
    ]
