# Generated by Django 4.0.1 on 2022-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0025_feedingtimesetup_delete_jstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingtime',
            name='food_total_setup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Food Total'),
        ),
        migrations.AddField(
            model_name='feedingtime',
            name='water_total_setup',
            field=models.IntegerField(blank=True, null=True, verbose_name='Water Total'),
        ),
        migrations.DeleteModel(
            name='FeedingTimeSetUp',
        ),
    ]
