# Generated by Django 4.0.1 on 2022-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0026_feedingtime_food_total_setup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeds',
            old_name='feed_name',
            new_name='feed_type',
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='feed_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
