# Generated by Django 4.0.1 on 2022-04-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0025_delete_jstest'),
        ('regular_tasks', '0027_rename_feed_name_feeds_feed_type_and_more'),
    ]

    operations = [
    ]
