# Generated by Django 4.0.1 on 2022-04-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0027_remove_feedingtime_food_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingtime',
            name='feeder_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='feeder amount'),
        ),
    ]
