# Generated by Django 4.0.1 on 2022-04-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0028_feedingtime_feeder_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='disinfectants',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_added',
            field=models.IntegerField(default=0, verbose_name='amount of food added'),
            preserve_default=False,
        ),
    ]
