# Generated by Django 4.0.1 on 2022-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0029_disinfectants_farm_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopcleaning',
            name='disinfectant',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
