# Generated by Django 4.0.1 on 2022-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0030_alter_coopcleaning_disinfectant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopcleaning',
            old_name='disinfectant',
            new_name='disinfectant_name',
        ),
    ]
