# Generated by Django 4.0.1 on 2022-05-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0031_rename_disinfectant_coopcleaning_disinfectant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeds',
            name='farm_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='qty_food',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
