# Generated by Django 4.0.1 on 2022-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0032_alter_feeds_farm_profile_alter_feeds_qty_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_added',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount of food added'),
        ),
    ]
