# Generated by Django 4.0.1 on 2022-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0033_alter_feedingtime_amount_food_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_added',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of food added'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of food consumed'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_food_rem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of food remaining'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_water_added',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of water added'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_water_consumed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of water consumed'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='amount_water_rem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of water remaining'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='feeder_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='feeder amount'),
        ),
        migrations.AlterField(
            model_name='feedingtime',
            name='water_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Water Total'),
        ),
    ]
