# Generated by Django 4.0.1 on 2022-05-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0034_alter_feedingtime_amount_food_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingtime',
            name='amount_water_added',
        ),
        migrations.RemoveField(
            model_name='feedingtime',
            name='amount_water_consumed',
        ),
        migrations.RemoveField(
            model_name='feedingtime',
            name='amount_water_rem',
        ),
        migrations.RemoveField(
            model_name='feedingtime',
            name='water_total',
        ),
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('amount_water_rem', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of water remaining')),
                ('amount_water_added', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of water added')),
                ('amount_water_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='amount of water consumed')),
                ('water_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Water Total')),
                ('notes', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flock_management.flocks')),
            ],
            options={
                'verbose_name_plural': 'Watering',
            },
        ),
    ]
