# Generated by Django 4.0.1 on 2022-05-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0005_rename_farm_id_coops_farm_profile_and_more'),
        ('profiles', '0009_alter_userprofile_city_country'),
        ('regular_tasks', '0035_remove_feedingtime_amount_water_added_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Watering',
            new_name='WateringTime',
        ),
        migrations.AlterModelOptions(
            name='wateringtime',
            options={},
        ),
    ]
