# Generated by Django 4.0.1 on 2022-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regular_tasks', '0036_rename_watering_wateringtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopcleaning',
            name='disinfectant_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
