# Generated by Django 4.0.1 on 2022-03-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0002_eggdeliverysalesdashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggroadsidesales',
            name='images_roadside_egg_sales',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='notes_roadside_egg_sales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
