# Generated by Django 4.0.1 on 2022-03-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0003_eggcollectionsales_images_eggcollectionsales_notes_and_more'),
        ('sales_and_income', '0003_eggroadsidesales_images_roadside_egg_sales_and_more'),
    ]

    operations = [
    ]
