# Generated by Django 4.0.1 on 2022-03-21 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0004_merge_20220321_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='images_roadside_egg_sales',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='notes_roadside_egg_sales',
        ),
    ]
