# Generated by Django 4.0.1 on 2022-03-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('sales_and_income', '0005_remove_eggroadsidesales_images_roadside_egg_sales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='sales_amount_eggs_roadside',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='sales_paid_difference_eggs_roadside',
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='farm_profile',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='amount_paid_eggs_roadside',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='dozen_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='half_dozen_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='loses_eggs_roadside',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_dozen_egg_boxes_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_dozen_egg_boxes_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_half_dozen_egg_boxes_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_half_dozen_egg_boxes_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_single_eggs_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_single_eggs_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_ten_egg_boxes_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_ten_egg_boxes_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_trays_of_eggs_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='qty_trays_of_eggs_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='single_egg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='ten_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggroadsidesales',
            name='trays_of_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
