# Generated by Django 4.0.1 on 2022-03-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0006_remove_eggroadsidesales_sales_amount_eggs_roadside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='farm_profile',
        ),
    ]
