# Generated by Django 4.0.1 on 2022-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0008_alter_eggdeliverysales_amount_paid_eggs_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eggcollectionsales',
            name='customer_name_eggs_collection',
        ),
        migrations.AlterField(
            model_name='eggcollectionsales',
            name='amount_paid_eggs_collection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollectionsales',
            name='balance_owed_eggs_collection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollectionsales',
            name='breakages_and_loses_eggs_collection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollectionsales',
            name='normal_order_qty_eggs_collection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollectionsales',
            name='qty_given_free_eggs_collection',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggcollectionsales',
            name='qty_sold_eggs_collection',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
