# Generated by Django 4.0.1 on 2022-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0010_rename_sales_amount_eggs_roadside_eggmarketsales_sales_amount_eggs_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggmarketsales',
            name='amount_paid_eggs_market',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='dozen_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='half_dozen_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='loses_eggs_market',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='qty_dozen_egg_boxes_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='qty_half_dozen_egg_boxes_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='qty_single_eggs_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='qty_ten_egg_boxes_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='qty_trays_of_eggs_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='sales_amount_eggs_market',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='sales_paid_difference_eggs_market',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='single_egg_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='ten_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='trays_of_eggs_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='eggmarketsales',
            name='venue_location_eggs_market',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
