# Generated by Django 4.0.1 on 2022-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0011_alter_eggmarketsales_amount_paid_eggs_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggdeliverysalesdashboard',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='eggdeliverysalesdashboard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
