# Generated by Django 4.0.1 on 2022-03-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0012_eggdeliverysalesdashboard_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('order_qty', models.IntegerField(blank=True, null=True)),
                ('route_day', models.DateField(blank=True, null=True)),
                ('route_position', models.IntegerField(blank=True, null=True)),
                ('single_egg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('six_egg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ten_egg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelve_egg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tray_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='eggcollectionsales',
            name='sale_amount_eggs_collection',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eggdeliverysales',
            name='sale_amount_eggs_delivery',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
