# Generated by Django 4.0.1 on 2022-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('sales_and_income', '0012_eggdeliverysalesdashboard_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eggroadsidesales',
            options={'verbose_name_plural': 'Egg roadside sales'},
        ),
        migrations.RenameField(
            model_name='eggroadsidesales',
            old_name='amount_paid_eggs_roadside',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='eggroadsidesales',
            old_name='qty_trays_of_eggs_added',
            new_name='qty_dozen_egg_boxes_sold',
        ),
        migrations.RenameField(
            model_name='eggroadsidesales',
            old_name='qty_trays_of_eggs_remaining',
            new_name='qty_half_dozen_egg_boxes_sold',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='dozen_eggs_price',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='half_dozen_eggs_price',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='single_egg_price',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='ten_eggs_price',
        ),
        migrations.RemoveField(
            model_name='eggroadsidesales',
            name='trays_of_eggs_price',
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_single_eggs_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_ten_egg_boxes_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_trays_eggs_added',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_trays_eggs_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_trays_eggs_sold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_egg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('half_dozen_eggs_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ten_eggs_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dozen_eggs_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trays_of_eggs_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
                ('sales_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_and_income.salestype')),
            ],
        ),
    ]
