# Generated by Django 4.0.1 on 2022-03-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0013_customer_and_more'),
    ]

    operations = [

    ]
