# Generated by Django 4.0.1 on 2022-03-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0013_salestype_alter_eggroadsidesales_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name_plural': 'Pricing'},
        ),
    ]
