# Generated by Django 4.0.1 on 2022-03-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0014_alter_pricing_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggroadsidesales',
            name='pricing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_and_income.pricing'),
            preserve_default=False,
        ),
    ]
