# Generated by Django 4.0.1 on 2022-03-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0015_eggroadsidesales_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_dozen_egg_boxes_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_half_dozen_egg_boxes_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_single_eggs_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_ten_egg_boxes_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eggroadsidesales',
            name='qty_trays_eggs_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
