# Generated by Django 4.0.1 on 2022-03-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0016_eggroadsidesales_qty_dozen_egg_boxes_in_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eggroadsidesales',
            old_name='loses_eggs_roadside',
            new_name='losses_eggs_roadside',
        ),
    ]
