# Generated by Django 4.0.1 on 2022-03-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0017_rename_loses_eggs_roadside_eggroadsidesales_losses_eggs_roadside'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggroadsidesales',
            name='income_deficit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
