# Generated by Django 4.0.1 on 2022-04-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0015_customerstatus_deliveryrouteday_and_more'),
        ('sales_and_income', '0018_eggroadsidesales_income_deficit'),
    ]

    operations = [
    ]
