# Generated by Django 4.0.1 on 2022-04-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('sales_and_income', '0019_merge_20220404_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_sales_type',
            field=models.ManyToManyField(to='sales_and_income.SalesType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customerstatus', to='sales_and_income.customerstatus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, related_name='farmprofile', to='profiles.farmprofile'),
            preserve_default=False,
        ),
    ]
