# Generated by Django 4.0.1 on 2022-04-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('sales_and_income', '0021_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerstatus',
            options={'verbose_name_plural': 'Customer Status'},
        ),
        migrations.AlterModelOptions(
            name='eggcollectionsales',
            options={'verbose_name_plural': 'Egg collection sales'},
        ),
        migrations.RenameField(
            model_name='eggcollectionsales',
            old_name='breakages_and_loses_eggs_collection',
            new_name='breakages_and_losses_eggs_collection',
        ),
        migrations.RemoveField(
            model_name='eggcollectionsales',
            name='normal_order_qty_eggs_collection',
        ),
        migrations.AddField(
            model_name='customer',
            name='order_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eggcollectionsales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_and_income.customer'),
        ),
        migrations.AddField(
            model_name='eggcollectionsales',
            name='farm_profile',
            field=models.ForeignKey(default=64, on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='farm_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile'),
        ),
    ]
