# Generated by Django 4.0.1 on 2022-04-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0020_alter_pricing_dozen_eggs_price_and_more'),
        ('sales_and_income', '0022_alter_customerstatus_options_and_more'),
    ]

    operations = [
    ]
