# Generated by Django 4.0.1 on 2022-04-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_and_income', '0023_merge_20220409_1144'),
        ('sales_and_income', '0023_merge_20220413_1203'),
    ]

    operations = [
    ]
