# Generated by Django 4.0.1 on 2022-04-13 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('expenditure', '0002_paymentmethods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure.paymentmethods'),
        ),
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount_withdrawn', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('farm_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenditure.paymentmethods')),
            ],
            options={
                'verbose_name_plural': 'Withdrawals',
            },
        ),
    ]
