# Generated by Django 4.0.1 on 2022-02-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0005_farmprofile_sales_units_dozen_carton_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_name', models.CharField(max_length=20)),
                ('identifier', models.CharField(blank=True, max_length=20, null=True)),
                ('coop_name', models.CharField(blank=True, max_length=20, null=True)),
                ('hens_qty', models.IntegerField(blank=True, null=True)),
                ('chicks_qty', models.IntegerField(blank=True, null=True)),
                ('cocks_qty', models.IntegerField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.breed')),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
            ],
        ),
    ]
