# Generated by Django 4.0.1 on 2022-02-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flocks',
            options={'verbose_name_plural': 'Flocks'},
        ),
    ]
