# Generated by Django 4.0.1 on 2022-03-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_userprofile_city_country'),
        ('flock_management', '0003_alter_flocks_farm_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flocks',
            name='coop_name',
        ),
        migrations.CreateModel(
            name='Coops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coop_name', models.CharField(max_length=20)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.farmprofile')),
            ],
            options={
                'verbose_name_plural': 'Coops',
            },
        ),
    ]
