# Generated by Django 4.0.1 on 2022-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flock_management', '0004_remove_flocks_coop_name_coops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coops',
            old_name='farm_id',
            new_name='farm_profile',
        ),
        migrations.RenameField(
            model_name='flocks',
            old_name='farm_id',
            new_name='farm_profile',
        ),
        migrations.AddField(
            model_name='flocks',
            name='coop',
            field=models.ManyToManyField(to='flock_management.Coops'),
        ),
    ]
